### ISSUE TITLE
Traffic Volume

### ISSUE THREAD

**Issue by samthehorseman** [raminmh/CfC#1]
Hi there, I have been fascinated by your models and have deeply enjoyed testing them out. 

Longshot but would you possibly be able to train the CfC models on the Traffic volume dataset (like you did with the LTC networks) please and post it on here so I could try it out?  

Thanks, Sam.

**Comment by raminmh** [comment]
Hello, happy to hear you like our work. 
I prepared the Traffic volume dataset. You can run CfC variants now simply by running `python3 traffic_with_cfc.py`. You can get SOTA performance with `--use_mixed` argument which uses the Mixed Memory CfC model. 

Enjoy! :)

**Comment by samthehorseman** [comment]
Hi
Thank you so much, I wasn’t expecting such a quick response and I’m very sorry for not replying to this earlier as my computer was unfortunately on the blink.
I was just wondering if you could release a version of this (the traffic model) where we could use our own optimizer because I’d like to further test it out with my favourite one:)

Thanks, Sam.
