### ISSUE TITLE
ncps.readthedocs errors on pytorch example

### ISSUE THREAD

**Issue by ray-5050** [raminmh/CfC#13]
On the page https://ncps.readthedocs.io/en/latest/examples/torch_first_steps.html

Under heading The LTC model with NCP wiring
wiring = AutoNCP(16, out_features)  # 16 units, 1 motor neuron
ltc_model = LTC(in_features, wiring, batch_first=True)
issue - out_features and in_features not defined
number of units appears to be 8 and out and in features are 1

under Training the model
issue - model undefined

**Comment by mlech26l** [comment]
Thanks for the info.

The correct way is

```python
trainer.fit(learn, dataloader)
```
