### ISSUE TITLE
Optimization

### ISSUE THREAD

**Issue by samthehorseman** [raminmh/CfC#2]
Hi
Thank you so much, I wasn’t expecting such a quick response and I’m very sorry for not replying to this earlier as my computer has unfortunately been on the blink for quite a while.
I was just wondering if you could release a version of this (the traffic model) where we could use our own optimizer because I’d like to further test it out with my favourite one:)

If you could mark in the code the optimum position to put the optimisation algorithm then I'd be further grateful for that too :)

Thanks, Sam.

**Comment by raminmh** [comment]
Hi, 
The code `traffic_with_cfc.py` already has an optimization module defined on lines 151-156. this can be changed to the optimization algorithm of your choice.

**Comment by samthehorseman** [comment]
Thank you, sorry for the rather stupid question. I should have looked more closely at the code and I'd like to apologize again.

Kind regards, Sam.
