### ISSUE TITLE
''--use_mixed_ltc'' function not found

### ISSUE THREAD

**Issue by LXRuuu** [raminmh/CfC#3]
Hello, I am very interested in your model. When I run your traffic_with_cfc.py, I found ''--use_mixed_ltc'', but I did not find the MixedLTCCell function in the code. I really want to know what it is, thank you

**Comment by raminmh** [comment]
Thank you for your interest in our work. MixedLTCCell is not included in this repo yet. Please stay put for some updates which will include that cell. In the meantime, please feel free to explore one of our documentation pages about our Liquid neural networks here: https://ncps.readthedocs.io/en/latest/
