### ISSUE TITLE
dataset not avaliable

### ISSUE THREAD

**Issue by mrcichon** [raminmh/CfC#4]
Hello,

The dataset seems to be unavailable (getting "Unable to establish SSL connection."  for https://pub.ist.ac.at/~mlechner/datasets/walker.zip).

**Comment by mlech26l** [comment]
Hi @mrcichon 
I have updated the URL in the downloading script. Can you check if it works now?

**Comment by mrcichon** [comment]
It's working correctly now. Thank you very much both for a speedy response and for your wonderful work.
