### ISSUE TITLE
Data preparation for the time series regression

### ISSUE THREAD

**Issue by PolKul** [raminmh/CfC#7]
I'm trying to adopt CfC network from your PyTorch example (person_atcivity) to make a timeseries regression. Given one dimensional array of floating-point numbers (lets consider them equally spaced in time) how can I feed them into the network? As I understand your current PyTorch implementation works as a classifier, that is the Labels array should be finite number of classes. But in case of regression we have floating point values as output. Also how should we structure the inputs? Lets say we have 10 last values of the timeseries as input and we want to predict 11th value, how do we do that? If you can provide a short pseudocode example it would be much appreciated. Thanks.

**Comment by nightvision04** [comment]
Agreed, a simple pseudocode example would be great. 

When this paper was reviewed for Nature, was there additional code supplied to the review team? If so, I would be happy to make a PR with some documentation.

**Comment by nightvision04** [comment]
@PolKul My latest fork does simple X,y prediction but includes significant refactoring.

**Comment by mlech26l** [comment]
@PolKul @nightvision04 the code in this repo is for reproducing/documenting the experiments of the paper.

A cleanup ready-to-use implementation of the CfCs with examples can be found here: https://ncps.readthedocs.io/en/latest/
I hope you will find the docs there useful

**Comment by raminmh** [comment]
Closing this issue with Mathias's link to our documentation page: https://ncps.readthedocs.io/en/latest/
